[tool.poetry]
name = "agent-executor"
version = "0.1.0"
description = ""
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.1"
langchain = {path = "../langchain/libs/langchain", develop = true}
python-magic = "^0.4.27"

[tool.poetry.group.dev.dependencies]
langchain-cli = {path = "../langchain/libs/cli", develop = true}

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
